### ISSUE TITLE
looks amazing; thanks

### ISSUE THREAD

**Issue by timelyportfolio** [keller-mark/anyhtmlwidget#24]
Sorry to pollute issues, but I did not know where to express my excitement for this project.  Looks amazing and love the idea.  I look forward to playing/experimenting and then helping (assuming you want help).  Thanks so much for your work on this.

Feel free to close this issue as soon as you see.  I'll plan to close in a couple of days.

**Comment by keller-mark** [comment]
Thanks, definitely open to contributions and help!

**Comment by keller-mark** [comment]
Probably slight preference for github for the purposes of making available to others/for easy future reference

**Comment by timelyportfolio** [comment]
Ok great.  I know some developers prefer to reserve issues for actual issues/problems and then discuss in Github discussions.  Are you ok with doing both in issues?  Or would you like to set up discussions to separate the two?

**Comment by keller-mark** [comment]
No major preference, I did not realize I had to activate the discussions but it should be working now

**Comment by timelyportfolio** [comment]
Perfect... closing.  Ok to share on social media, or too early?
